name: stellar_ecc
description: Stellar ECC — privacy-first, ephemeral, end-to-end encrypted messenger.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # State management
  flutter_riverpod: ^2.5.1

  # Routing
  go_router: ^14.2.0

  # Cryptography
  libsignal_protocol_dart: ^0.4.0
  cryptography: ^2.7.0
  pointycastle: ^3.9.1
  crypto: ^3.0.6

  # Local encrypted storage
  sqlite3: ^2.4.6
  sqlcipher_flutter_libs: ^0.6.4
  path_provider: ^2.1.3
  path: ^1.9.0

  # Secure storage
  flutter_secure_storage: ^9.2.2

  # Networking
  web_socket_channel: ^3.0.1
  http: ^1.2.2

  # Calls
  flutter_webrtc: ^0.11.6

  # Attachments
  image_picker: ^1.1.2
