name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Inspect libsignal wrapper
        run: |
          sed -n '1,80p' ~/.pub-cache/hosted/pub.dev/libsignal_protocol_dart-0.7.1/lib/src/protocol/sender_key_distribution_message_wrapper.dart

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: stellar-ecc-apk
          path: build/app/outputs/flutter-apk/app-release.apk
